# Generated by Django 5.1.7 on 2025-03-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_phone', models.CharField(max_length=10)),
                ('order_date', models.DateField(verbose_name='date')),
                ('appointment_no', models.CharField(max_length=1)),
                ('service', models.TextField()),
            ],
        ),
    ]
