# Generated by Django 5.1.7 on 2025-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('start', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_no',
            field=models.CharField(max_length=1, verbose_name='預約時段'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=20, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=10, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='預約日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.TextField(verbose_name='服務項目'),
        ),
    ]
